#!/usr/bin/env ruby

require 'centuria'

module Cent
  class CLI < Thor
    map %w[-v --version] => :__version
    desc "[-v, --version]", "you can confirm the version of Centuria"
    
    def __version
      puts "Centuria #{Centuria.gem_version}"
    end
    
    register(Create, "new", "new [NAME]", "you can generate text file for memo")
    register(Clear, "clear", "clear [NAME]", "you can destroy file or directory")
  end
end

Cent::CLI.start(ARGV)