#!/usr/bin/env ruby

require 'centuria'

module Cent
  class CLI < Thor
    package_name "Centuria"
    
    default_command :default
    class_option :version, aliases: '-v', type: :boolean, default: false
    class_option :help, aliases: '-h', type: :boolean, default: false
    
    desc "", "default command"
    def default
      if ARGV == %w(-v) || ARGV == %w(--version)
        say "Centuria #{Centuria.version}"
      else
        self.help
      end
    end
    
    register(Create, "new", "new [NAME]", "you can generate text file for memo")
    register(Clear, "clear", "clear [NAME]", "you can destroy file or directory")
    register(Tinker, "tinker", "tinker", "you can use console include Centuria")
  end
end

Cent::CLI.start(ARGV)