#!/usr/bin/env ruby

require 'centuria'

module Cent
  class CLI < Thor
    package_name "Centuria"
    
    map %w[-v --version] => :__version
    desc "[-v, --version]", "you can confirm the version of Centuria"
    
    def __version
      puts "Centuria #{Centuria.gem_version}"
    end
    
    register(Create, "new", "new [NAME]", "you can generate text file for memo")
    register(Clear, "clear", "clear [NAME]", "you can destroy file or directory")
    register(Tinker, "tinker", "tinker", "you can use console include Centuria")
  end
end

Cent::CLI.start(ARGV)